"""empty message

Revision ID: 062f6971d0c3
Revises: ef8a9fcb0578
Create Date: 2021-07-21 21:35:22.963782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '062f6971d0c3'
down_revision = 'ef8a9fcb0578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('test', 'completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('test', 'create_date')
    # ### end Alembic commands ###
