"""empty message

Revision ID: 16af7230c4bd
Revises: c5d6dbb5d8a4
Create Date: 2021-07-21 14:09:38.589474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16af7230c4bd'
down_revision = 'c5d6dbb5d8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('timer', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('totalWordCount', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('wordsPerMin', sa.Integer(), nullable=True))
    op.drop_column('test', 'tag')
    op.drop_column('test', 'author')
    op.drop_column('test', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('test', 'wordsPerMin')
    op.drop_column('test', 'totalWordCount')
    op.drop_column('test', 'timer')
    # ### end Alembic commands ###
