"""empty message

Revision ID: 888bcb077846
Revises: 3c1103e30de9
Create Date: 2021-07-16 23:34:43.364251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888bcb077846'
down_revision = '3c1103e30de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'tag')
    # ### end Alembic commands ###
